Feat: Create python-app.yml
SouJunior/stars-api pull request #3
Opened 2024-05-13 23:11 UTC by JessiAraujo

Adicionando GitHub Actions padrão para python
Adcionado verificação de formatação com a lib black e padrão pep8
Adcionado verificação do pytest com 100% de coverage
Adcionado verificação do flake8

2024-05-13 23:19 UTC, JessiAraujo commented
Neste pull request, foram adicionadas as seguintes funcionalidades:

- Implementação do GitHub Actions padrão para automação de construção e teste do aplicativo Python.
- Adição da verificação de formatação de código com a lib Black, seguindo o padrão PEP8.
- Inclusão da verificação de testes com o pytest, garantindo uma cobertura de 100% do código.
- Integração da verificação de qualidade de código com o Flake8, identificando possíveis problemas e fornecendo sugestões de melhoria.

2024-05-17 18:34 UTC, LucasGasque requested changes

2024-05-17 18:34 UTC, LucasGasque commented on .github/workflows/python-app.yml
> +        pytest --cov=. --cov-report=term
falta adicionar a falha se a cobertura estiver abaixo de 100%
--cov=. ele ira ver a cobertura dos repositórios raiz, o correto é usar apenas o repositório app

2024-05-17 18:34 UTC, LucasGasque commented on .github/workflows/python-app.yml
> +    - name: Test with pytest
Não precisa testar 2 vezes, o "job" de baixo já testa o código

2024-05-17 18:34 UTC, LucasGasque commented on .github/workflows/python-app.yml
> +    - name: Verify with flake8
o Job de cima já verifica o flake8, pode deletar esse job

2024-05-22 10:02 UTC, LucasGasque requested changes
Porque esse arquivo foi deletado?

2024-05-22 10:03 UTC, LucasGasque commented on .docker/docker-compose.yml
> -services:
Porque esse arquivo foi deletado?

2024-05-22 10:04 UTC, LucasGasque commented on README.md
>  # stars-api
sempre que for instalar uma lib, deve se antes entrar no ambiente virtual venv, isso deve estar na documentação

2024-05-25 00:09 UTC, JessiAraujo commented on .docker/docker-compose.yml
> -services:
o arquivo docker-compose foi excluído erroneamente. 

O arquivo foi retornado para o pasta docker.

2024-05-27 12:27 UTC, LucasGasque reviewed
Solicitação de algumas mudanças

2024-05-27 12:27 UTC, LucasGasque commented on .docker/docker-compose.yml
> -    name: mysql_database
não tem problema

2024-05-27 12:27 UTC, LucasGasque commented on .gitignore
> +app/some_module.py
Geralmente o gitigonre não é utilizado para ignorar pastas pessoais, essas não devem ser commitadas
ele deve ser utilizado para pastas gerais que não devem subir

vc adicionou 1 pasta e 1 arquivo que não deveriam estár aqui

você pode subir o pytest.ini para o git, para que seus colegas rodem o mesmo comando que sera rodado na esteira quendo eles forem escrever os testes unitários

a pasta tests/ é onde vamos fazer nossos testes unitários, portanto ela não deve estar no gitignore

então vc precisa excluir essas linhas, pode subir o arquivo pytest.ini e pode subir a pasta tests, desde que esteja vazia

2024-10-22 20:25 UTC, merged