Feature/pydantic settings
SouJunior/stars-api pull request #4
Opened 2024-05-16 00:51 UTC by stephacastro

Implementação do pydantic-settings

2024-06-04 22:30 UTC, stephacastro commented
Demanda implementação do pydantic settings.

2024-06-05 12:10 UTC, LucasGasque requested changes

2024-06-05 12:10 UTC, LucasGasque commented on app/main.py
> +print('teste')
Remove essa linha por favor

2024-06-05 12:10 UTC, LucasGasque commented on app/requirements.txt
> +annotated-types==0.6.0
o que é esse arquivo?
já existe um requirements na raiz do projeto

2024-06-05 12:10 UTC, LucasGasque commented on app/settings.py
> +    class config:
Essa configuração class config é do pydantic versão 1
o pydantic_settings v2 usa outra notação
https://docs.pydantic.dev/latest/concepts/pydantic_settings/#usage

2024-06-05 12:10 UTC, LucasGasque commented on requirements.txt
> -alembic==1.13.1
Porque você está excluindo a lib alembic?
pode desfazer todas essas mudanças e adicionar apenas a lib pydantic-settings

2024-06-05 12:10 UTC, LucasGasque commented on app/settings.py
> +        env_prexix = 'DB_'
Qual a função desse parâmetro?

Nem todas as variáveis de ambiente terão esse prefixo
pode remover

2024-06-05 12:10 UTC, LucasGasque commented on app/settings.py
> +class Settings(BaseSettings):
a classe Settings deve ser privada __Settings, para evitar que ela seja importada em outros módulos

2024-06-05 12:10 UTC, LucasGasque commented on app/database.py
> +settings = Settings()
vamos instanciar esse objeto no arquivo dele, e vamos importar o objeto e não a classe!

2024-06-06 10:13 UTC, LucasGasque requested changes
Algumas mudanças

2024-06-06 10:13 UTC, LucasGasque commented on app/database.py
>  from dotenv import load_dotenv
pode excluir as linhas 7 e 9 do load_dotenv não vamos precisar dele

2024-06-06 10:13 UTC, LucasGasque commented on app/main.py
>  load_dotenv()
excluir o load_dotenv e o import

2024-06-06 10:13 UTC, LucasGasque commented on app/settings.py
> +def get_settings():
pode excluir essa função, não precisa criar função para instanciar uma classe

pode fazer direto settings = __Settings()

2024-06-06 10:13 UTC, LucasGasque commented on app/settings.py
> +load_dotenv()
excluir o load_dotenv e o import dele e o import os

2024-06-06 10:13 UTC, LucasGasque commented on app/settings.py
> +    DB_DATABASE: str
faltou a configuração da classe para pegar as variáveis de ambiente do .env

vc pode usar o campo model_config e a classe SettingsConfigDIct conforme a documentação do pydantic settings
https://docs.pydantic.dev/latest/concepts/pydantic_settings/#usage

vc já até fez o import da classe e não usou

2024-06-06 10:13 UTC, LucasGasque commented on requirements.txt
> +load-dotenv==0.1.0
pode excluir a lib load-dotenv não vamos usa-la

2024-06-10 10:07 UTC, LucasGasque approved these changes
Parabéns, aprovado!

2024-06-10 23:22 UTC, merged

2024-06-10 23:22 UTC, stephacastro commented
obrigada!